clone:
  clone:
    image: 325714046698.dkr.ecr.eu-west-1.amazonaws.com/dmx/drone-git:next
    pull: true

pipeline:
  build:
    image: openjdk:8-jdk
    commands:
      - "apt-get update"
      - "apt-get install -y maven"
      - "mvn package"

  s3-sandbox:
    image: plugins/s3
    acl: public-read
    region: "eu-west-1"
    bucket: "skyscanner-sandbox-skymetrics-deploymentsupport"
    secrets:
      - source: access_key_sandbox
        target: aws_access_key_id
      - source: secret_key_sandbox
        target: aws_secret_access_key
    source: target/opentsdb-tdigests-3.2.0-SNAPSHOT.jar
    strip_prefix: target/
    target: "/histograms/tdigests/dev-build-${DRONE_BUILD_NUMBER}/"
    when:
      event:
        include: pull_request
      branch:
        exclude: master

  s3-prod:
    image: plugins/s3
    acl: public-read
    region: "eu-west-1"
    bucket: "skyscanner-prod-skymetrics-deploymentsupport"
    secrets:
      - source: access_key
        target: aws_access_key_id
      - source: secret_key
        target: aws_secret_access_key
    source: target/opentsdb-tdigests-3.2.0-SNAPSHOT.jar
    strip_prefix: target/
    target: "/histograms/tdigests/release-build-${DRONE_BUILD_NUMBER}/"
    when:
      branch: master
      event:
        exclude: pull_request